# Generated by Django 5.2 on 2025-04-12 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок объявления")),
                ("description", models.TextField(verbose_name="Описание товара")),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="ad_images", verbose_name="Изображение"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("одежда", "Одежда"),
                            ("обувь", "Обувь"),
                            ("аксессуары", "Аксессуары"),
                            ("хобби", "Хобби"),
                            ("электроника", "Электроника"),
                            ("для дома и дачи", "Для дома и дачи"),
                            ("запчасти", "Запчасти"),
                            ("товары для детей", "Товары для детей"),
                            ("красота и здоровье", "Красота и здоровье"),
                        ],
                        max_length=30,
                        verbose_name="Категория товара",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("новый", "Новый"), ("б/у", "Б/у")], max_length=10, verbose_name="Состояние товара"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания объявления")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель объявления",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.CreateModel(
            name="ExchangeProposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(verbose_name="Комментарий")),
                ("status", models.CharField(default="Ожидает", max_length=15, verbose_name="Статус")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания объявления")),
                (
                    "ad_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="receiver_exchange_proposals",
                        to="ads.ad",
                        verbose_name="На что менять",
                    ),
                ),
                (
                    "ad_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="sender_exchange_proposals",
                        to="ads.ad",
                        verbose_name="Что менять",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предложение обмена",
                "verbose_name_plural": "Предложения обмена",
            },
        ),
    ]
